DROP TABLE IF EXISTS game_stats CASCADE;
DROP TABLE IF EXISTS player_hero CASCADE;
DROP TABLE IF EXISTS game CASCADE;
DROP TABLE IF EXISTS match CASCADE;
DROP TABLE IF EXISTS player CASCADE;
DROP TABLE IF EXISTS team CASCADE;
DROP TABLE IF EXISTS tournament CASCADE;
DROP TABLE IF EXISTS hero CASCADE;
DROP TABLE IF EXISTS item CASCADE;
DROP TABLE IF EXISTS game_item_stats CASCADE;
DROP TABLE IF EXISTS match_type CASCADE;
DROP TABLE IF EXISTS admin CASCADE;

CREATE TABLE public.admin (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp(6) without time zone,
    email character varying(255),
    last_login timestamp(6) without time zone,
    password_hash character varying(255),
    username character varying(255)
);

CREATE TABLE public.team (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp(6) without time zone,
    logo_url character varying(255),
    name character varying(255),
    rating double precision,
    region character varying(255)
);

CREATE TABLE public.tournament (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    end_date date,
    name character varying(255),
    organizer character varying(255),
    prize_pool double precision,
    start_date date
);

CREATE TABLE public.hero (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    attack_type character varying(255),
    logo_url character varying(255),
    name character varying(255),
    primary_attribute character varying(255),
    roles character varying(255)
);

CREATE TABLE public.item (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    cost integer,
    description character varying(255),
    logo_url character varying(255),
    name character varying(255)
);

CREATE TABLE public.match_type (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    type_name character varying(255)
);

CREATE TABLE public.match (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    best_of integer,
    match_date date,
    match_type_id bigint REFERENCES public.match_type(id) ON DELETE SET NULL,
    team_dire_id bigint REFERENCES public.team(id) ON DELETE CASCADE,
    team_radiant_id bigint REFERENCES public.team(id) ON DELETE CASCADE,
    tournament_id bigint REFERENCES public.tournament(id) ON DELETE CASCADE
);

CREATE TABLE public.player (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    country character varying(255),
    nickname character varying(255),
    real_name character varying(255),
    role character varying(255),
    team_id bigint REFERENCES public.team(id) ON DELETE SET NULL
);

CREATE TABLE public.player_hero (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    games_played integer,
    hero_id bigint REFERENCES public.hero(id) ON DELETE CASCADE,
    player_id bigint REFERENCES public.player(id) ON DELETE CASCADE
);

CREATE TABLE public.game (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    duration integer,
    start_time timestamp(6) without time zone,
    winner character varying(255),
    match_id bigint REFERENCES public.match(id) ON DELETE CASCADE
);

CREATE TABLE public.game_stats (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    assists integer,
    deaths integer,
    final_level integer,
    gold_per_minute integer,
    kills integer,
    last_hits integer,
    net_worth double precision,
    xp_per_minute integer,
    game_id bigint REFERENCES public.game(id) ON DELETE CASCADE,
    player_hero_id bigint REFERENCES public.player_hero(id) ON DELETE CASCADE
);

CREATE TABLE public.game_item_stats (
    id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    quantity integer,
    game_stats_id bigint REFERENCES public.game_stats(id) ON DELETE CASCADE,
    item_id bigint REFERENCES public.item(id) ON DELETE CASCADE
);

-- Примечание: На данном этапе таблицы созданы и ограничения добавлены корректно.