name: SonarCloud Analysis
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11 (для Spring)
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'

      - name: Build Spring project
        run: |
          cd spring-project-folder
          ./mvnw clean verify

      - name: Set up Node.js (для React)
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install React dependencies
        run: |
          cd react-project-folder
          npm install

      - name: Run SonarCloud analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner -Dproject.settings=sonar-project.properties
